spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 260ds4rif6lr5o2niusfor5t7o
            clientSecret: e2ak9lgj651rvafoq6shgg9ff52sm5fddtlo304e09j53gn96ge
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            clientName: SpringAppClient
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_R7RBorwr2
            user-name-attribute: cognito:username
          google:
            client-id: 468501143863-4rofbun992d1hvfv84jmc4ilmln9m7k9.apps.googleusercontent.com
            client-secret: n8Gn1h31Q_CArFPZxJjIme3t




  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cognito
    username: postgres
    password: root

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true





#
#  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#  spring.jpa.hibernate.ddl-auto=create
#  spring.jpa.hibernate.show-sql=true
#  spring.datasource.url=jdbc:postgresql://localhost:5432/test1
#  spring.datasource.username=postgres
#  spring.datasource.password=root
#  should be populated as per our User Pool and App Client created on AWS.
#
