spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 3kfrbopv2ql5pgj5u2bvb68rul
            clientSecret: raqimoes8f40q7drd820448fls63bc6plp0lou1b7bqem11bht1
            scope: openid
            redirectUriTemplate: http://localhost:8080/login/oauth2/code/cognito
            clientName: spring-boot-backend
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_uX7Ozh3rZ
            userNameAttribute: cognito:username # or just username
